version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}  # Alterado de DB_NAME para DB_DATABASE
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - sqlserver
    volumes:
      - .:/app

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "cacula123"  # Mantenha uma senha forte aqui
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
